### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Liftoff-Studios** [smj-edison/ka-api#4]
Hi, does this still work
Because KA seems to have changed the rules for fkey and I am able to get this to work 

Could you help

**Comment by smj-edison** [comment]
I believe it still works... I've updated the code to use the GraphQL authentication backend, but it still uses the old API for creating programs and working with comments. I haven't tested their API in a while, so I'm not sure if it has migrated or not...

**Comment by Liftoff-Studios** [comment]
I tried login, it doesn't work

**Comment by Liftoff-Studios** [comment]
I don't get the KAAS only Kavid

**Comment by smj-edison** [comment]
I just tested the login code, it appears to be working. Are you using a normal KA account (not google) for the login?

Here's some sample code to try out (change the username and password):
```javascript
const {login} = require("ka-api").auth;
const {newProgram} = require("ka-api").programs;

let _ = (async function() {
    console.log("logging in...");
    let cookies = await login("username", "password");
    console.log("logged in");
    
    await newProgram(cookies, "// Put code here\n\n\n", {
        title: "New program",
        translatedTitle: "New program",
    }, "pjs");
)();
```

To use ka-api as a node dependency use `"ka-api": "github:smj-edison/ka-api"` in the dependencies section of `package.json`.

If all works that should create a program with a comment in it. If not could you post any error logs?

**Comment by Liftoff-Studios** [comment]
Ok I'll try and tell

**Comment by Liftoff-Studios** [comment]
Thanks, it works now
